import type { LucideIcon } from "lucide-react";
import {
  Calculator,
  Cake,
  TrendingUp,
  Receipt,
  Ruler,
  ArrowLeftRight,
  Sun,
  Crop,
  FileSpreadsheet,
  PersonStanding,
  Flame,
  Utensils,
  Percent,
  Weight,
  Beef,
  Footprints,
  HeartPulse,
  TrendingDown,
  Sigma,
  PiggyBank,
  Repeat,
  ShieldCheck,
  Target,
  PercentCircle,
  QrCode,
  Globe2,
  Timer,
  Gift,
  Home,
  Building2,
  CalendarRange,
  Type,
} from "lucide-react";

export const categoryOrder = [
  "Health and Fitness",
  "Finance",
  "Social Media",
  "Measurements",
  "Real Estate",
  "Miscellaneous",
  "Business",
] as const;

export type ToolCategory = (typeof categoryOrder)[number];

export interface ToolMeta {
  slug: string;
  name: string;
  shortName: string;
  /** Whether this tool displays monetary values in the visitor's chosen display currency. */
  usesCurrency?: boolean;
  description: string;
  icon: LucideIcon;
  category: ToolCategory;
}

export const tools: ToolMeta[] = [
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    shortName: "BMI",
    description: "Check your body mass index and healthy weight range.",
    icon: PersonStanding,
    category: "Health and Fitness",
  },
  {
    slug: "bmr-calculator",
    name: "BMR Calculator",
    shortName: "BMR",
    description: "Find your resting metabolic rate and calories by activity level.",
    icon: Flame,
    category: "Health and Fitness",
  },
  {
    slug: "calorie-calculator",
    name: "Calorie Calculator",
    shortName: "Calories",
    description: "Get your daily calorie target and macro split for your goal.",
    icon: Utensils,
    category: "Health and Fitness",
  },
  {
    slug: "body-fat-calculator",
    name: "Body Fat Percentage Calculator",
    shortName: "Body Fat",
    description: "Estimate body fat percentage using the U.S. Navy method.",
    icon: Percent,
    category: "Health and Fitness",
  },
  {
    slug: "ideal-body-weight-calculator",
    name: "Ideal Body Weight Calculator",
    shortName: "Ideal Weight",
    description: "Compare your ideal weight range across four medical formulas.",
    icon: Weight,
    category: "Health and Fitness",
  },
  {
    slug: "protein-intake-calculator",
    name: "Protein Intake Calculator",
    shortName: "Protein",
    description: "Work out your daily protein target based on activity level.",
    icon: Beef,
    category: "Health and Fitness",
  },
  {
    slug: "steps-calculator",
    name: "Steps to Calories/Distance Calculator",
    shortName: "Steps",
    description: "Convert your daily step count into distance and calories burned.",
    icon: Footprints,
    category: "Health and Fitness",
  },
  {
    slug: "biological-age-calculator",
    name: "Biological Age Calculator",
    shortName: "Bio Age",
    description: "Estimate your wellness age from lifestyle habits.",
    icon: HeartPulse,
    category: "Health and Fitness",
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    shortName: "EMI",
    description: "Work out monthly loan instalments, interest and payoff totals.",
    icon: Calculator,
    category: "Finance",
    usesCurrency: true,
  },
  {
    slug: "sip-calculator",
    name: "SIP Calculator",
    shortName: "SIP",
    description: "Project the future value of your monthly investments.",
    icon: TrendingUp,
    category: "Finance",
    usesCurrency: true,
  },
  {
    slug: "tax-calculator",
    name: "Tax Calculator",
    shortName: "Tax",
    description: "Estimate income tax under the old and new regimes.",
    icon: Receipt,
    category: "Finance",
  },
  {
    slug: "loan-prepayment-calculator",
    name: "Loan Prepayment Calculator",
    shortName: "Prepayment",
    description: "See how a part-payment reduces your tenure or EMI.",
    icon: TrendingDown,
    category: "Finance",
    usesCurrency: true,
  },
  {
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    shortName: "Compound Interest",
    description: "Project growth with flexible compounding frequency.",
    icon: Sigma,
    category: "Finance",
    usesCurrency: true,
  },
  {
    slug: "fd-calculator",
    name: "Fixed Deposit (FD) Calculator",
    shortName: "FD",
    description: "Work out the maturity value of a fixed deposit.",
    icon: PiggyBank,
    category: "Finance",
    usesCurrency: true,
  },
  {
    slug: "rd-calculator",
    name: "Recurring Deposit (RD) Calculator",
    shortName: "RD",
    description: "Work out the maturity value of a recurring deposit.",
    icon: Repeat,
    category: "Finance",
    usesCurrency: true,
  },
  {
    slug: "ppf-calculator",
    name: "PPF Calculator",
    shortName: "PPF",
    description: "Project your Public Provident Fund maturity value.",
    icon: ShieldCheck,
    category: "Finance",
    usesCurrency: true,
  },
  {
    slug: "goal-sip-calculator",
    name: "Goal-Based SIP Calculator",
    shortName: "Goal SIP",
    description: "Find the monthly SIP needed to hit a target amount.",
    icon: Target,
    category: "Finance",
    usesCurrency: true,
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    shortName: "Percentage",
    description: "Percentage of a value, share of a total, or percent change.",
    icon: PercentCircle,
    category: "Finance",
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    shortName: "Cropper",
    description: "Crop images by hand, or auto-generate perfectly sized social media assets.",
    icon: Crop,
    category: "Social Media",
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    shortName: "Units",
    description: "Convert length, weight, temperature, speed and more.",
    icon: Ruler,
    category: "Measurements",
  },
  {
    slug: "solar-panel-calculator",
    name: "Solar Panel Calculator",
    shortName: "Solar",
    description: "Size a rooftop solar system from your electricity bill.",
    icon: Sun,
    category: "Miscellaneous",
    usesCurrency: true,
  },
  {
    slug: "currency-converter",
    name: "Currency Converter",
    shortName: "Currency",
    description: "Exchange rates across major world currencies, updated hourly.",
    icon: ArrowLeftRight,
    category: "Miscellaneous",
  },
  {
    slug: "birthday-reminder",
    name: "Birthday Reminder",
    shortName: "Birthdays",
    description: "Never miss a birthday — track upcoming ones at a glance.",
    icon: Cake,
    category: "Miscellaneous",
  },
  {
    slug: "salary-slip-maker",
    name: "Salary Slip Maker",
    shortName: "Salary Slip",
    description: "Build a professional salary slip and export it as JPG or PDF.",
    icon: FileSpreadsheet,
    category: "Business",
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    shortName: "QR Code",
    description: "Turn any text or URL into a downloadable QR code.",
    icon: QrCode,
    category: "Business",
  },
  {
    slug: "timezone-converter",
    name: "Time Zone Converter",
    shortName: "Time Zone",
    description: "Convert a date and time between any two time zones.",
    icon: Globe2,
    category: "Business",
  },
  {
    slug: "countdown-timer",
    name: "Countdown Timer",
    shortName: "Countdown",
    description: "Live countdown to any date and time.",
    icon: Timer,
    category: "Business",
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    shortName: "Age",
    description: "Exact age in years, months and days, plus your next birthday.",
    icon: Gift,
    category: "Business",
  },
  {
    slug: "rent-vs-buy-calculator",
    name: "Rent vs Buy Calculator",
    shortName: "Rent vs Buy",
    description: "Compare the true cost of renting against buying a home.",
    icon: Home,
    category: "Real Estate",
    usesCurrency: true,
  },
  {
    slug: "property-tax-calculator",
    name: "Property Tax Calculator",
    shortName: "Property Tax",
    description: "Estimate your annual property tax from value and rate.",
    icon: Building2,
    category: "Real Estate",
    usesCurrency: true,
  },
  {
    slug: "date-difference-calculator",
    name: "Date Difference Calculator",
    shortName: "Date Difference",
    description: "Find the exact time span between any two dates.",
    icon: CalendarRange,
    category: "Miscellaneous",
  },
  {
    slug: "word-counter",
    name: "Word & Character Counter",
    shortName: "Word Counter",
    description: "Count words, characters, sentences and estimate reading time.",
    icon: Type,
    category: "Miscellaneous",
  },
];

export function getToolBySlug(slug: string): ToolMeta | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(): { category: ToolCategory; tools: ToolMeta[] }[] {
  return categoryOrder.map((category) => ({
    category,
    tools: tools.filter((tool) => tool.category === category),
  }));
}
